# The container includes:
#
# azukiapp/node:
# * Node 5.2.0
# * NPM 3.3.12
#

FROM alpine:3.3
MAINTAINER Anniel Menezes <contato@annielmenezes.com>

RUN apk update && apk upgrade
RUN apk add nodejs=4.3.0-r0

CMD ["node"]
