# The container includes:
#
# azukiapp/node:
# * Node 5.2.0
# * NPM 3.3.12
#

FROM alpine
MAINTAINER Anniel Menezes <contato@annielmenezes.com>

RUN apk update && apk upgrade
RUN apk add nodejs

CMD ["node"]
